var getMyDiv = document.getElementById("container");
var createHeading = document.createElement("h2");
createHeading.textContent = "A basic HTML table";
getMyDiv.appendChild(createHeading);
var createTable = document.createElement("table");
createTable.style = "width : 100%";
getMyDiv.appendChild(createTable);
var createTr1 = document.createElement("tr");
createTable.appendChild(createTr1);
var createTr2 = document.createElement("tr");
createTable.appendChild(createTr2);
var createTr3 = document.createElement("tr");
createTable.appendChild(createTr3);
var createTh = document.createElement("th");
createTh.textContent = "Company";
createTr1.appendChild(createTh);
var createTh = document.createElement("th");
createTh.textContent = "Contact";
createTr1.appendChild(createTh);
var createTh = document.createElement("th");
createTh.textContent = "Country";
createTr1.appendChild(createTh);
var createTd = document.createElement("td");
createTd.textContent = "Alfreds Futterkiste";
createTr2.appendChild(createTd);
var createTd = document.createElement("td");
createTd.textContent = "Maria Anders";
createTr2.appendChild(createTd);
var createTd = document.createElement("td");
createTd.textContent = "Germany";
createTr2.appendChild(createTd);
var createTd = document.createElement("td");
createTd.textContent = "Centro comercial Moctezuma";
createTr3.appendChild(createTd);
var createTd = document.createElement("td");
createTd.textContent = "Francisco Chang";
createTr3.appendChild(createTd);
var createTd = document.createElement("td");
createTd.textContent = "Mexico";
createTr3.appendChild(createTd);